export const FeaturesData = [
  {
    id: 1,
    image:
      "https://img.icons8.com/fluency-systems-regular/64/000000/retro-tv.png ",
    title: "Web Development",
    desc: "I throw myself down among the tall grass by the stream as I lie close to the earth.",
  },
  {
    id: 2,
    image: "https://img.icons8.com/material-outlined/64/000000/topic--v1.png ",
    title: "Mobile App",
    desc: "There are many variations of passages of Lorem Ipsum	available, but the majority.",
  },
  {
    id: 3,
    image: "https://img.icons8.com/ios/40/000000/open-book.png",
    title: "App Development",
    desc: " It uses a dictionary of over 200 Latin words, combined witha handful of model sentence.",
  },
  {
    id: 4,
    image: "https://img.icons8.com/ios/64/000000/menu.png",
    title: "Business Stratagy",
    desc: "I throw myself down among the tall grass by the stream as I lie close to the earth.",
  },
  {
    id: 5,
    image: "https://img.icons8.com/ios-filled/64/000000/wifi.png ",
    title: "CEO Marketing",
    desc: "always free from repetition, injected humour, or non-characteristic words etc.",
  },
  {
    id: 6,
    image: "https://img.icons8.com/glyph-neue/50/000000/polyline.png ",
    title: "Personal Portfolio April",
    desc: " It uses a dictionary of over 200 Latin words, combined with a handful of model sentence.",
  },
];

export const PortfolioData = [
  {
    id: 1,
    category: "DEVELOPMENT",
    totalLike: "600",
    title: "The services provide for design ",
    image: "./images/app.jpg",
  },
  {
    id: 2,
    category: "WEB DESIGN",
    totalLike: "280",
    title: "Design for tecnology & services",
    image: "./images/web.jpg",
  },
  {
    id: 3,
    category: "APPLICATION",
    totalLike: "750",
    title: "Mobile app landing design & maintain",
    image: "./images/mobile.jpg",
  },
  {
    id: 4,
    category: "PHOTOSHOP",
    totalLike: "630",
    title: "Logo design creativity & Application ",
    image: "./images/photoshop.jpg",
  },
  {
    id: 5,
    category: "FIGMA",
    totalLike: "360",
    title: "Mobile app landing design & Services",
    image: "./images/app.jpg",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "./images/web.jpg",
  },
];

export const ExperienceData = [
  {
    id: 1,
    color: "success",
    company: "Flair Labs",
    location: "Mumbai",
    designation: "Associate Software Engineer",
    startDate: "July 2021",
    endDate: "Present",
    description: ["Learned React", "Earned Money"],
  },
  {
    id: 2,
    company: "GeeksforGeeks",
    color: "secondary",
    location: "Noida",
    designation: "Technical Content Writer",
    startDate: "July 2021",
    endDate: "Sep 2021",
    description: ["Learned React", "Earned Money"],
  },
  {
    id: 3,
    company: "Fcreation LLP",
    color: "secondary",
    location: "Mumbai",
    designation: "PHP Developer",
    startDate: "Dec 2020",
    endDate: "July 2021",
    description: ["Learned React", "Earned Money"],
  },
];

export const TestimonialData = [
  {
    id: 1,
    image: "./image/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 2,
    image: "./image/slide2.png",
    design: "Default name",
    name: "Davei Luace",
    offcer: "Chief Operating Manager",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 3,
    image: "./image/slide3.png",
    design: "Rainbow-Themes",
    name: "Nevine Acotanza",
    offcer: "Chief Operating Officer",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 4,
    image: "./image/slide4.png",
    design: "Bound - Trolola",
    name: "Jone Duone Joe",
    offcer: "Operating Officer",
    post: "Web App Development",
    date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 5,
    image: "./image/slide5.png",
    design: "Glassfisom",
    name: "Nevine Dhawan",
    offcer: "CEO Of Officer",
    post: "Android App Design",
    date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
];
